import { renderCharge, renderChargeThumbnail } from './charge-view.mjs';
import { renderBlueprint, renderBlueprintThumbnail } from './blueprint-view.mjs';
import { renderPattern, renderPatternThumbnail } from './pattern-view.mjs';

const pattern = (kind) => ({
  render: (demo) => renderPattern(demo, kind),
  thumbnail: (id) => renderPatternThumbnail(kind, id),
  styles: ['pattern.css', 'encounter.css'],
  scripts: ['pattern-player.mjs'],
});
const blueprint = (mechanicId) => ({
  render: (demo) => renderBlueprint(demo, mechanicId),
  thumbnail: (id) => renderBlueprintThumbnail(mechanicId, id),
  styles: ['blueprint.css', 'encounter.css'],
  scripts: ['blueprint-player.mjs'],
});
// A new animation registers a server-rendered accessible diagram and its browser assets here.
export const animations = {
  charge: {
    render: renderCharge,
    thumbnail: renderChargeThumbnail,
    styles: ['charge.css', 'encounter.css'],
    scripts: ['charge-player.mjs'],
  },
  sweep: pattern('sweep'),
  'ground-slam': pattern('ground-slam'),
  summon: pattern('summon'),
  'gap-volley': pattern('gap-volley'),
  'projectile-fan': pattern('projectile-fan'),
  'landing-jump': blueprint('landing-jump'),
  'single-shot': blueprint('single-shot'),
  crossfire: blueprint('crossfire'),
  'splitting-projectile': blueprint('splitting-projectile'),
  'returning-projectile': blueprint('returning-projectile'),
  'orbiting-projectiles': blueprint('orbiting-projectiles'),
  'pulse-beam': blueprint('pulse-beam'),
  'chain-explosions': blueprint('chain-explosions'),
  mine: blueprint('mine'),
  'moving-hazard': blueprint('moving-hazard'),
  'converging-threats': blueprint('converging-threats'),
  pull: blueprint('pull'),
  'turret-deployment': blueprint('turret-deployment'),
  'threat-generator': blueprint('threat-generator'),
  decoy: blueprint('decoy'),
  'predictive-aiming': blueprint('predictive-aiming'),
  'source-tracking': blueprint('source-tracking'),
  'burst-fire': blueprint('burst-fire'),
  volley: blueprint('volley'),
  'delayed-activation': blueprint('delayed-activation'),
  'speed-change': blueprint('speed-change'),
  'limited-spread': blueprint('limited-spread'),
  'directional-shield': blueprint('directional-shield'),
  'damage-type-resistance': blueprint('damage-type-resistance'),
  'situational-immunity': blueprint('situational-immunity'),
  'part-break': blueprint('part-break'),
  'attack-reflection': blueprint('attack-reflection'),
  'counter-stance': blueprint('counter-stance'),
  'absorption-power-up': blueprint('absorption-power-up'),
  'interruptible-wind-up': blueprint('interruptible-wind-up'),
  'loadout-adaptation': blueprint('loadout-adaptation'),
  'wind-up': blueprint('wind-up'),
  'attack-lock': blueprint('attack-lock'),
  'wide-swing': blueprint('wide-swing'),
  lunge: blueprint('lunge'),
  grab: blueprint('grab'),
  'burrow-and-emerge': blueprint('burrow-and-emerge'),
  'ring-volley': blueprint('ring-volley'),
  'spiral-barrage': blueprint('spiral-barrage'),
  'ricochet-projectile': blueprint('ricochet-projectile'),
  'homing-projectile': blueprint('homing-projectile'),
  'straight-beam': blueprint('straight-beam'),
  'scanning-beam': blueprint('scanning-beam'),
  'rotating-beams': blueprint('rotating-beams'),
  'marked-area-strike': blueprint('marked-area-strike'),
  shockwave: blueprint('shockwave'),
  'lingering-hazard': blueprint('lingering-hazard'),
  'hazard-trail': blueprint('hazard-trail'),
  'platform-destruction': blueprint('platform-destruction'),
  'shrinking-safe-area': blueprint('shrinking-safe-area'),
  knockback: blueprint('knockback'),
  'target-lock': blueprint('target-lock'),
  'attack-combination': blueprint('attack-combination'),
  'weak-point': blueprint('weak-point'),
  telegraph: blueprint('telegraph'),
  'fight-phase': blueprint('fight-phase'),
  enrage: blueprint('enrage'),
};
