import { renderCharge, renderChargeThumbnail } from './charge-view.mjs';
import { renderBlueprint, renderBlueprintThumbnail } from './blueprint-view.mjs';
import { renderPattern, renderPatternThumbnail } from './pattern-view.mjs';

const pattern = (kind) => ({
  render: (demo) => renderPattern(demo, kind),
  thumbnail: (id) => renderPatternThumbnail(kind, id),
  styles: ['pattern.css', 'encounter.css'],
  scripts: ['pattern-player.mjs'],
});
const blueprint = (mechanicId) => ({
  render: (demo) => renderBlueprint(demo, mechanicId),
  thumbnail: (id) => renderBlueprintThumbnail(mechanicId, id),
  styles: ['blueprint.css', 'encounter.css'],
  scripts: ['blueprint-player.mjs'],
});
// A new animation registers a server-rendered accessible diagram and its browser assets here.
export const animations = {
  charge: {
    render: renderCharge,
    thumbnail: renderChargeThumbnail,
    styles: ['charge.css', 'encounter.css'],
    scripts: ['charge-player.mjs'],
  },
  sweep: pattern('sweep'),
  'ground-slam': pattern('ground-slam'),
  summon: pattern('summon'),
  'gap-volley': pattern('gap-volley'),
  'projectile-fan': pattern('projectile-fan'),
  'landing-jump': blueprint('landing-jump'),
  'single-shot': blueprint('single-shot'),
  crossfire: blueprint('crossfire'),
  'splitting-projectile': blueprint('splitting-projectile'),
  'returning-projectile': blueprint('returning-projectile'),
  'orbiting-projectiles': blueprint('orbiting-projectiles'),
  'pulse-beam': blueprint('pulse-beam'),
  'chain-explosions': blueprint('chain-explosions'),
  mine: blueprint('mine'),
  'moving-hazard': blueprint('moving-hazard'),
  'converging-threats': blueprint('converging-threats'),
  pull: blueprint('pull'),
  'turret-deployment': blueprint('turret-deployment'),
  'threat-generator': blueprint('threat-generator'),
  decoy: blueprint('decoy'),
  'predictive-aiming': blueprint('predictive-aiming'),
  'source-tracking': blueprint('source-tracking'),
  'burst-fire': blueprint('burst-fire'),
  volley: blueprint('volley'),
  'delayed-activation': blueprint('delayed-activation'),
  'speed-change': blueprint('speed-change'),
  'limited-spread': blueprint('limited-spread'),
  'directional-shield': blueprint('directional-shield'),
  'damage-type-resistance': blueprint('damage-type-resistance'),
  'situational-immunity': blueprint('situational-immunity'),
  'part-break': blueprint('part-break'),
  'attack-reflection': blueprint('attack-reflection'),
  'counter-stance': blueprint('counter-stance'),
  'absorption-power-up': blueprint('absorption-power-up'),
  'interruptible-wind-up': blueprint('interruptible-wind-up'),
  'loadout-adaptation': blueprint('loadout-adaptation'),
  'wind-up': blueprint('wind-up'),
  'attack-lock': blueprint('attack-lock'),
  'active-phase': blueprint('active-phase'),
  recovery: blueprint('recovery'),
  'survival-phase': blueprint('survival-phase'),
  teleport: blueprint('teleport'),
  'boundary-attack': blueprint('boundary-attack'),
  'forced-scrolling': blueprint('forced-scrolling'),
  'chase-herding': blueprint('chase-herding'),
  'escape-phase': blueprint('escape-phase'),
  'relocated-arena': blueprint('relocated-arena'),
  'control-mode-shift': blueprint('control-mode-shift'),
  'boss-as-terrain': blueprint('boss-as-terrain'),
  'cover-line-of-sight': blueprint('cover-line-of-sight'),
  'forced-inertia': blueprint('forced-inertia'),
  'wraparound-projectile': blueprint('wraparound-projectile'),
  'beat-synced-attack': blueprint('beat-synced-attack'),
  'secondary-cues-invisibility': blueprint('secondary-cues-invisibility'),
  'sound-detection': blueprint('sound-detection'),
  'objective-linked-invulnerability': blueprint('objective-linked-invulnerability'),
  'wave-clear-objective': blueprint('wave-clear-objective'),
  'environmental-weapon': blueprint('environmental-weapon'),
  'encounter-specific-tool': blueprint('encounter-specific-tool'),
  'player-controlled-boss': blueprint('player-controlled-boss'),
  'projectile-rally': blueprint('projectile-rally'),
  'baited-self-hit': blueprint('baited-self-hit'),
  'posture-stagger-gauge': blueprint('posture-stagger-gauge'),
  'pacifist-resolution': blueprint('pacifist-resolution'),
  'persistent-progress': blueprint('persistent-progress'),
  'status-buildup': blueprint('status-buildup'),
  'instant-kill': blueprint('instant-kill'),
  'maximum-health-reduction': blueprint('maximum-health-reduction'),
  'ability-lock': blueprint('ability-lock'),
  'resource-steal': blueprint('resource-steal'),
  'on-hit-healing': blueprint('on-hit-healing'),
  'self-heal-cast': blueprint('self-heal-cast'),
  'external-healing-source': blueprint('external-healing-source'),
  'damage-rate-cap': blueprint('damage-rate-cap'),
  'loadout-mirror': blueprint('loadout-mirror'),
  'moveset-shapeshifting': blueprint('moveset-shapeshifting'),
  'ally-theft': blueprint('ally-theft'),
  'false-death': blueprint('false-death'),
  'action-reactive-punish': blueprint('action-reactive-punish'),
  'run-history-manifestation': blueprint('run-history-manifestation'),
  'real-time-progression': blueprint('real-time-progression'),
  'interface-interaction': blueprint('interface-interaction'),
  'world-state-variant': blueprint('world-state-variant'),
  'party-size-scaling': blueprint('party-size-scaling'),
  'partner-revival': blueprint('partner-revival'),
  'kill-order-inheritance': blueprint('kill-order-inheritance'),
  'shared-group-health': blueprint('shared-group-health'),
  'coordinated-duo-attack': blueprint('coordinated-duo-attack'),
  'stack-damage': blueprint('stack-damage'),
  'wide-swing': blueprint('wide-swing'),
  lunge: blueprint('lunge'),
  grab: blueprint('grab'),
  'burrow-and-emerge': blueprint('burrow-and-emerge'),
  'ring-volley': blueprint('ring-volley'),
  'spiral-barrage': blueprint('spiral-barrage'),
  'ricochet-projectile': blueprint('ricochet-projectile'),
  'homing-projectile': blueprint('homing-projectile'),
  'straight-beam': blueprint('straight-beam'),
  'scanning-beam': blueprint('scanning-beam'),
  'rotating-beams': blueprint('rotating-beams'),
  'marked-area-strike': blueprint('marked-area-strike'),
  shockwave: blueprint('shockwave'),
  'lingering-hazard': blueprint('lingering-hazard'),
  'hazard-trail': blueprint('hazard-trail'),
  'platform-destruction': blueprint('platform-destruction'),
  'shrinking-safe-area': blueprint('shrinking-safe-area'),
  knockback: blueprint('knockback'),
  'target-lock': blueprint('target-lock'),
  'attack-combination': blueprint('attack-combination'),
  'weak-point': blueprint('weak-point'),
  telegraph: blueprint('telegraph'),
  'fight-phase': blueprint('fight-phase'),
  enrage: blueprint('enrage'),
};
